# Copyright (C) 2022 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# https://kubernetes.io/docs/concepts/services-networking/network-policies
# https://hub.armosec.io/docs/c-0054
# https://hub.armosec.io/docs/c-0049
# Kein "NetworkPolicy controller" durch Docker Desktop, z.B. Calico, Cilium, Antrea

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "verlag.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  # Spezifikation, auf welche Pods die NetworkPolicy angewendet wird
  podSelector:
    matchLabels:
      {{- include "verlag.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: autor
              app.kubernetes.io/name: autor
              app.kubernetes.io/instance: autor
      ports:
        - port: 8080
          protocol: TCP
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgres
              app.kubernetes.io/name: postgres
              app.kubernetes.io/instance: postgres
      ports:
        - port: 5432
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: mysql
              app.kubernetes.io/name: mysql
              app.kubernetes.io/instance: mysql
      ports:
        - port: 3306
          protocol: TCP
