# Copyright (C) 2021 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker compose [-f compose.yml -f compose.eclipse.yml|compose.azul.yml|compose.buildpacks-eclipse.yml|compose.buildpacks-eclipse.yml] up
#           docker compose exec verlag bash
#             id
#             ps -ef
#             env
#             ls -l /layers
#             ls -l
#             pwd
#             hostname
#             cat /etc/os-release
#           docker compose down

# https://docs.docker.com/compose/compose-file
# https://docs.docker.com/compose/compose-file/compose-file-v3
# https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json

# https://docs.docker.com/compose/compose-file/05-services
services:
  verlag:
    image: floriansauer/verlag:2023.10.0-buildpacks
    ports:
      #- published: 8080-8085 würden wir mehrere Container verwenden. Dann bräuchten wir auch mehrere Ports.
      - published: 8080
        target: 8080
    volumes:
      - type: bind
        source: ..\..\..\src\main\resources\application.yml # vorteil: können von außen was verändern
        target: /workspace/BOOT-INF/classes/application.yml
        read_only: true
      - type: bind
        source: ..\..\..\src\main\resources\private-key.pem
        target: /workspace/BOOT-INF/classes/private-key.pem
        read_only: true
      - type: bind
        source: ..\..\..\src\main\resources\certificate.crt
        target: /workspace/BOOT-INF/classes/certificate.crt
        read_only: true
      - type: bind
        source: C:\Zimmermann\volumes\verlag # docker container ist nur readonly; tomcat kann nur schreiben, wenn volume auf host eingebunden wird
        target: /tmp
    env_file: verlag.env
    # CAVEAT: bei Replikation keine doppelten Rechnernamen im virtuellen Netzwerk !!!
    hostname: verlag # nur möglich, weil wir nur eine instanz laufen lasen
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#cap_add-cap_drop
    cap_drop: [ ALL ] # alle kernel kapabilities weg; laufender Container sicherer
    stop_grace_period: 10s # grace = tolerantes zeitinterval beim herunterfahren des servers; zu verarbeitende requests noch abarbeiten und keine neuen requests abarbeiten.
    # https://docs.docker.com/compose/compose-file/deploy
    deploy:
      # https://docs.docker.com/compose/compose-file/deploy/#resources
      resources:
        limits: # harte obergrenze
          cpus: "2.0"
          memory: 1024M
        reservations: # standard; minimum
          cpus: "0.5"
          memory: 512M
      # https://docs.docker.com/compose/compose-file/deploy/#replicas
      #mode: replicated replikationsmodus; z.B. zwei Container starten.
      #replicas: 2
      #endpoint_mode: vip
